services:
  backend:
    container_name: todo_api_container
    build: .
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${PORT}:3000
    restart: always
    volumes:
      - .:/app

